{ pkgs, lib, config, inputs, ... }:

{
  # Native libraries and tools needed to build and test sangward.
  packages = [
    pkgs.git
    pkgs.pkg-config
    pkgs.gtk4
    pkgs.libadwaita
    pkgs.glib
    pkgs.dbus
    pkgs.just
    pkgs.jq
    pkgs.curl
    pkgs.bitwarden-cli
    pkgs.vaultwarden
    pkgs.xvfb-run
    pkgs.xorg.xauth
    # Harness TLS: bw refuses plain-http servers, so Vaultwarden runs with a throwaway CA.
    pkgs.openssl
    # Isolated session bus for the GTK smoke test.
    pkgs.dbus
    pkgs.procps
    pkgs.coreutils
  ];

  languages.rust = {
    enable = true;
    # Reads rust-toolchain.toml, so the dev shell, CI and releases all use the
    # same pinned version. Do not also set channel/version here.
    toolchainFile = ./rust-toolchain.toml;
  };

  # Test-harness configuration. The justfile reads these; nothing is hard-coded there.
  env = {
    SW_VW_ADDRESS = "127.0.0.1";
    SW_VW_PORT = "8087";
    # HTTPS: the official bw CLI (2026.x) rejects non-TLS servers outright.
    SW_VW_URL = "https://localhost:8087";
    SW_VW_ALIVE_URL = "https://localhost:8087/alive";
    # Test-only admin token for the throwaway local Vaultwarden instance.
    SW_VW_ADMIN_TOKEN = "sangward-test-admin-token-not-secret";
    # All harness state lives under target/ so `cargo clean` wipes it.
    SW_HARNESS_DIR = "${config.devenv.root}/target/harness";
    SW_VW_PID_FILE = "${config.devenv.root}/target/vaultwarden.pid";
    SW_FIXTURES = "${config.devenv.root}/target/fixtures.json";
    # Throwaway CA generated by `just harness-up`; trusted only by harness processes.
    SW_CA_CERT = "${config.devenv.root}/target/harness/tls/ca.pem";
    # Test users (throwaway credentials for the local harness only).
    SW_TEST_USER1_EMAIL = "pbkdf2.user@example.test";
    SW_TEST_USER1_PASSWORD = "Correct-Horse-Battery-Pbkdf2!";
    SW_TEST_USER2_EMAIL = "Argon2.User@Example.test";
    SW_TEST_USER2_PASSWORD = "Tr0ub4dor&3-Argon2id-Sentinel";
    # Large-vault user for UI/agent performance tests.
    SW_TEST_USER3_EMAIL = "large.vault@example.test";
    SW_TEST_USER3_PASSWORD = "Large-Vault-Perf-Pbkdf2#5k";
    SW_LARGE_VAULT_ITEMS = "5000";
    # Main-loop stall budget for the GTK UI tests (ms). One frame at 60 Hz is ~16 ms;
    # this allows for Xvfb + debug builds while still catching multi-second freezes.
    SW_UI_MAX_STALL_MS = "150";
  };

  enterShell = ''
    echo "sangward dev shell: $(rustc --version), just $(just --version 2>/dev/null)"
  '';
}
